# Generated by Django 3.2.7 on 2021-11-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tomeet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('done_for', models.BigIntegerField()),
                ('today', models.DateField()),
                ('important', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
