# Generated by Django 3.2.7 on 2021-11-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211107_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='habits',
            name='done_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habits',
            name='today',
            field=models.DateTimeField(),
        ),
    ]
